### ISSUE TITLE
About the dataset.

### ISSUE THREAD

**Issue by ruizewang** [Sampson-Lee/myDRGAN#1]
Hello Sampson, 
could you please me some details about the dataset you used when you trained the model?

**Comment by Sampson-Lee** [comment]
Hi, @22881916 

I upload the txt file of dataset, which may provide useful information.

**Comment by ruizewang** [comment]
OK, thank you very much Sampson. It helps me a lot.

**Comment by 22881916** [comment]
多谢大佬哈哈哈！
